### PR TITLE
fixed /proc/kmsg: permission denied in syslog-ng

### PR DESCRIPTION
**Pull request by sokoow**
I've just fixed default syslog-ng config and a minor sshd fix.

### CODE REVIEW

**Comment by pragmaticivan** [comment]
ping, I'm having this error too.

**Comment by pragmaticivan** [comment]
cc @FooBarWidget

**Comment by Theaxiom** [comment]
@sokoow This PR has merge conflicts, please resolve those conflicts and let me know so I can merge your changes in! :)

Is there an existing issue that this PR is in reference to? If not, please kindly open a new issue which explains what you are trying to accomplish with these changes.

**Comment by lucafavatella** [comment]
The syslog part of this PR seems already addressed by #382.
I would suggest to close this PR and open new PR with the sshd part of this PR (if still applicable - I do not use sshd).

**Comment by Theaxiom** [comment]
@lucafavatella Thank you for the heads-up!

**Pull request closed without merging**
