### PR TITLE
Improve pep8 compliance

### PR DESCRIPTION
**Pull request by josegonzalez**
This changeset fixes PEP8 issues, minus `E501 line too long (80 > 79 characters)`, as that should be more of a guideline than a strict rule, and harder to follow without silly refactoring.

Also removed two unused exception variables.

A cleaner diff can be seen [here](https://github.com/phusion/baseimage-docker/pull/399/files?w=1), which drops most of the whitespace changes.

### CODE REVIEW

**Comment by hyperknot** [comment]
Wow, I just wanted to dedicate some time to finally do this! It's great!

I'd enter at least a new lines after the shebang line though. I wonder why it's using `-u` for unbuffered output, but maybe it's better not to touch it at this point.

**Comment by josegonzalez** [comment]
@hyperknot Probably so that output comes out in order.

**Comment by hyperknot** [comment]
OK, I went through the same process and ended up with almost the same file. I'd personally not make short parameters into multiple lines, like:

    pid = os.spawnl(os.P_NOWAIT,
                    "/usr/bin/runsvdir",
                    "/usr/bin/runsvdir",
                    "-P",
                    "/etc/service")

or 

            pid = os.spawnvp(os.P_NOWAIT,
                             args.main_command[0],
                             args.main_command)

or 

parser.add_argument(
    'main_command',
    metavar='MAIN_COMMAND',
    type=str,
    nargs='*',
    help='The main command to run. (default: runit)')

I find those much harder to read than it would be in a one or two line version.

**Comment by Theaxiom** [comment]
Thanks @josegonzalez !

**Pull request merged**
