### PR TITLE
Multiarch implementation for amd64, arm64 and arm32

### PR DESCRIPTION
**Pull request by CodeCutterUK**
As promised in #518 here is a potential change to support multiple architectures.

I couldn't see a `next` branch as per contribution guidelines so based this off of `master` instead.

### CODE REVIEW

**Comment by CodeCutterUK** [comment]
I might be able to change this to store the individual builds with Travis until the manifest is deployed, which would get around needing the Docker username and password, but will await initial feedback

**Comment by kingdonb** [comment]
I would like to take some time to review this, but unfortunately don't have access to any ARM hosts or other than AMD64 right now, for at least several months.  Is there someone who can vouch for this who has some of the architectures in question?

**Comment by Theaxiom** [comment]
@CodeCutterUK yeah sorry, contribution guidelines need to be updated -- we don't have `next` branch anymore as it is simplified with trunk-based development (feature/task-based branching) flow. We really appreciate the contribution, I am tempted to just merge it in and then fail forward if it doesn't work. What do you think @kingdonb ?

**Comment by CodeCutterUK** [comment]
Happy to fix forward....only thing to be aware of is that I can't test the Docker Hub publication parts, so might be worth double checking the publish to `latest` & `master` parts work as expected and don't overwrite anything.

**Comment by Theaxiom** [comment]
Changes have been merged in.

**Pull request merged**
