### PR TITLE
Start syslog-ng before runit, and stop after runit.

### PR DESCRIPTION
**Pull request by sundbry**
Use Case: I had a problem with my app dropping logs to the central log server which syslog-ng was forwarding to, when containers were restarting.

Problem: When syslog-ng is managed as an runit service, application logs may be
lost during shutdown, when the syslog-ng service stops before the app
exits. 

Solution: This change uses the my_init.d directory to manage syslog-ng at a lower
runlevel than runit.

### CODE REVIEW

**Comment by sundbry** [comment]
Request for comments?

**Comment by Theaxiom** [comment]
@hyperknot or @kingdonb ?

**Comment by hyperknot** [comment]
Sorry, this doesn't make sense for me. The key line is:

```
/etc/init.d/syslog-ng start
```

In there, telling System V init to start the service, but we are not even using sysvinit. Our init system is runit.

If you'd like to prioritise services maybe we can do some kind of kind of support for 10_syslog_ng, 20_cron, 30_sshd like naming convention and start them manually or something similar, but it's not possible to start something before the init process.

**Comment by sundbry** [comment]
@hyperknot This is just piggybacking on the default init script, which takes care of the pid file and a status check to wait for a successful syslog startup, and allows us to signal the process to gracefully stop. It is less code to maintain, the original (removed) script in the .runit file was essentially copied from this script to begin with. It does not cause any interference, or fork a whole sysvinit.

**Comment by hyperknot** [comment]
@sundbry but the default init script should be a sequence of blocking scripts, that is not background processes. 

The question with background processes is that what is their parent process and who is supervising them.

**Comment by jwilson8767** [comment]
I believe this functionality is already available [via runit](http://smarden.org/runit/faq.html#depends) without removing syslog-ng as a runit service.

**Comment by sundbry** [comment]
@jwilson8767 the suggested runit style solution of coding the syslog dependency into the application's init script does not solve the shutdown order dependency. The primary purpose of this PR is to prevent application logs from being truncated at container shutdown when syslog-ng stops before the 'userspace' services have exited.

**Comment by Theaxiom** [comment]
What is the consensus around this PR?

**Comment by kingdonb** [comment]
I haven't had a chance to look at it again, but I'm inclined to say go ahead and merge it because it looks like the submitter has done his homework, and truncating the logs is kind of a nasty problem.

**Comment by kingdonb** [comment]
There should be a way to ensure that starting syslog-ng via init.d still results in the creation of the appropriate pid file, or whatever runit is looking for, to result in `sv status` being able to report back on the status of the daemon.  How soon are we trying to push 0.9.23?

**Comment by Theaxiom** [comment]
`0.9.23` will be released this week, but this can always be pushed to the next release.

**Comment by hyperknot** [comment]
I really don't agree with this PR, as it introduces two separate service supervisors into one container. Making everything double, complicated and bloated.

**Comment by kingdonb** [comment]
It's not really two separate supervisors though is it?

Well... but it is though, right?  The processes that runit didn't spawn, it also can't reap forked children from.  So it's actually important that the processes spawn from runit to the whole "supervisor cleans up after its children" proposition.  That's part of the reason why runit services are supposed to be foreground processes, because it's waiting for them to exit, "supervising" them, and restarting them as needed when they exit without being stopped.

Is there any way to prevent the log truncation without going outside of runit?

**Comment by sundbry** [comment]
That's a pure mental point about the two separate supervisors, the root
supervisor is my_init, which cleans up after its children in its shutdown
routine. Runit has it's utility in making user applications very convenient
to program to start and stop. Beyond that, it has it's limitations, as in
this situation where shutdown sequencing is important.

**Comment by kingdonb** [comment]
I agree with @hyperknot that the change makes me uncomfortable, but truncated logs makes me unhappy too.  I would be more comfortable if it added documentation of the problem with runit.

As it is now, if we merge this change then users who want to restart syslog-ng need to know at least that the syslog can't be restarted interactively with an `sv restart` and will need to be restarted a different way.  That isn't documented anywhere.

@sundbry Would you be willing to add a commit to the README that describes the shutdown sequencing issue (since you appear to know intricately how it fails) and explains why the decision to launch syslog a different way was made?

I'm OK with the idea of doing a different thing where it's appropriate, but it can't be undocumented.  We go back and look at code all the time and say "why was this unusual thing done this way?" and if we can't figure it out from the comments in the code or the README, we'll end up put it back the way it was (read: subtly broken.)

**Comment by sundbry** [comment]
@kingdonb No problem, pushed.

I also set the syslog script to start with 10_ so the order is fixed and it matches the /etc/my_init.d/00_regen_ssh_host_keys.sh script.

This should also fix issue #436 (Lost log messages in docker logs) for reference.

**Comment by sundbry** [comment]
There will still be a problem with the syslog-forwarder, however, since that service is still not synchronized. I have experimented with syslog-ng.conf to output directly to the docker console, without any luck yet, but may address that in a separate PR.

**Comment by sundbry** [comment]
So this breaks logging to the docker console with https://github.com/phusion/baseimage-docker/pull/438, since the syslog-ng stdout pipe is not getting to the console.

Please do not merge, I will have to revise.

**Comment by sundbry** [comment]
This latest commit will preserve the STDOUT file descriptor, so the logs forward completely to the docker output.

I have also removed the call to init.d, and it no longer uses start-stop-daemon to supervise because of it.

```text
$ docker run phusion/baseimage:0.9.22
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Oct 31 22:42:35 a25d8e4afa0b syslog-ng[11]: syslog-ng starting up; version='3.5.6'
Oct 31 22:42:36 a25d8e4afa0b syslog-ng[11]: EOF on control channel, closing connection;
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 17
Oct 31 22:42:36 a25d8e4afa0b cron[20]: (CRON) INFO (pidfile fd = 3)
Oct 31 22:42:36 a25d8e4afa0b cron[20]: (CRON) INFO (Running @reboot jobs)


^C*** Shutting down runit daemon (PID 17)...
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
Oct 31 22:42:45 a25d8e4afa0b syslog-ng[11]: syslog-ng shutting down; version='3.5.6'
Oct 31 22:42:45 a25d8e4afa0b syslog-ng[11]: EOF on control channel, closing connection;
*** Killing all processes...
`

**Comment by hyperknot** [comment]
Can someone check the memory usage before vs. after this PR?

**Comment by sundbry** [comment]
```text
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.5  32312 10676 ?        Ss   18:09   0:00 /usr/bin/python
root        11  0.0  0.3  72376  7824 ?        S    18:09   0:00 /usr/sbin/syslo
root        17  0.0  0.0   4400  1188 ?        S    18:09   0:00 /usr/bin/runsvd
root        18  0.0  0.0   4248   672 ?        Ss   18:09   0:00 runsv cron
root        19  0.0  0.0   4248   656 ?        Ss   18:09   0:00 runsv sshd
root        20  0.0  0.1  29276  2868 ?        S    18:09   0:00 /usr/sbin/cron
```

There's no change here, a few kb less maybe since there's no runsv for syslog-ng.

**Comment by Theaxiom** [comment]
Thanks @sundbry for your diligence and hard work, it is greatly appreciated! I have merged this into master now. Thank you @hyperknot and @kingdonb for your contributions as well and ensuring that only the highest quality contributions make it into release. 👍

**Comment by hyperknot** [comment]
Also, please raise the minor version to 0.10.0 as this is breaking compatibility with child images. We should also document somewhere that lines like:

```
touch /etc/service/syslog-ng/down
rm -rf /etc/service/syslog-ng
```

Will have no effect, and need to be changed. 

Also 
```
touch /etc/service/syslog-forwarder/down
```

Will break the build since that folder no longer exists.

**Pull request merged**
