### PR TITLE
https://github.com/phusion/baseimage-docker/issues/391

### PR DESCRIPTION
**Pull request by tgranqvist**

### CODE REVIEW

**Comment by Theaxiom** [comment]
Argh looks like it broke the build: https://travis-ci.org/phusion/baseimage-docker/builds/221640311

**Comment by Theaxiom** [comment]
Looks like something hinky is going on. I will have to check it out tomorrow. I don't think your change broke the build. https://github.com/phusion/baseimage-docker/pull/393

**Comment by tgranqvist** [comment]
This was my first pull request, so I might have messed things up. As I said in the original thread, I fixed it locally and tested, all was good. I merged the edits in my local image per these instructions: https://gist.github.com/glamp/74188691c91d52770807. And the Python code is clearly wrong :)

**Comment by Theaxiom** [comment]
Yeah, as I said, I don't believe you broke it. I reverted your changes and the build is still failing. Something weird is going on and I will check it out tomorrow. Your contribution is greatly appreciated, thank you!

**Comment by tgranqvist** [comment]
My pleasure and thanks for the quick responses!

**Pull request merged**
