### PR TITLE
Delete double args

### PR DESCRIPTION
**Pull request by bdod**
I found duplicate arguments in the command. 
It does not look like they need it here, thanks.

### CODE REVIEW

**Comment by kingdonb** [comment]
This looks like a correct change to me, but I am not a python guy...

Can anyone else confirm this is a simple error (and not something that was put this way on purpose?)

**Comment by apalmalarrain** [comment]
I write most of my code in Python but had never seen os.spawnl before. Duplicating the executable path as first argument seems to be the right way to go about it according to the [official documentation](https://docs.python.org/3.6/library/os.html#os.spawnl), though there's no mention of it outside of the code example. I'm not sure why, or where else to look.

If anything, that line of code has been touched over 7 commits, one of which (892dcc7) even changed the command to execute, and all contain the duplicate.

**Comment by apalmalarrain** [comment]
Actually, I misread.

At the end of the fourth paragraph of the section I linked to:
>  In either case, the arguments to the child process must start with the name of the command being run.

**Comment by bdod** [comment]
Oh, thank's. 
My mistake , I will be more attentive in the future

**Pull request closed without merging**
