### PR TITLE
Revise the README_ZH_cn version

### PR DESCRIPTION
**Pull request by OhCoder**
Hello, I revised the first several paragraphs. :)

### CODE REVIEW

**Comment by FooBarWidget** [comment]
Thanks. Can't read your changes, but whatever. :)

**Comment by FooBarWidget** [comment]
Hm, there is apparently a merge conflict. Can you rebase against master?

**Comment by OhCoder** [comment]
I update my fork version to the newest, and create a new branch under my fork project, now I can rebase my new branch to my master......

**Comment by FooBarWidget** [comment]
All right, merged now.

**Pull request merged**
