### PR TITLE
runit policy with /etc/sv and /etc/service

### PR DESCRIPTION
**Pull request by javyer**
runit use /etc/service and /etc/sv directory

To enable a service : ln -s /etc/sv/foo /etc/service
To disable : rm /etc/service/foo

http://smarden.org/runit/faq.html#remove
http://smarden.org/runit/faq.html#tell

### CODE REVIEW

**Comment by javyer** [comment]
Hello Travis,
I was adding other services to runit, and digging how to enable or disable services. From runit docs, we can read that /etc/service is only used to link files from /etc/sv. So to unify the way we manage service files, I have changed the way phusion add services to runit to do it in the way that runit is expecting.
It's useful if you are using other runit services ...

**Comment by hyperknot** [comment]
I think these are needed when you are regularly adding and removing services in a real server. For our Docker based environment not using symbolic links is a cleaner and less bug-prone way to set up. Same can be said for nginx config, etc. No need to overcomplicate things here.

**Comment by Theaxiom** [comment]
@hyperknot Would you mind joining my Mattermost chat instance? I setup a channel for `baseimage-docker`. I would like to discuss this project with you as I am the new maintainer and you seem quite active. You also had your own fork and I would like to combine our efforts. You can join using this link: http://mattermost.dynamictivity.com/signup_user_complete/?id=pjksr6h977n4zxxyto3ojp8twa

Thanks!

**Comment by Theaxiom** [comment]
@javyer I am inclined to agree with @hyperknot on this, while we do appreciate the contribution I don't see the justification for adding the unnecessary complexity. If you do have a valid reason, by all means, please let me know. Thanks!

**Comment by hyperknot** [comment]
@Theaxiom sure, I'll try to join on mattermost tomorrow, I've already registered! Great work!

**Pull request closed without merging**
