### PR TITLE
Reflect 'latest' in imagelayers.io image.

### PR DESCRIPTION
**Pull request by jondot**

### CODE REVIEW

**Comment by kingdonb** [comment]
If we are building these from master, should address #434 before somebody winds up with default SSH keys in their production container with a custom path for my_init.d

(Would that possibly happen?  And could it be dangerous @hyperknot)

**Comment by Theaxiom** [comment]
@kingdonb I don't think this PR has any bearing on that. This is simply a link to a third-party.

**Comment by kingdonb** [comment]
@theaxiom No, I'm sure it doesn't, but if we are pushing out "latest" from master via CI and weren't before, ...

**Comment by hyperknot** [comment]
@kingdonb not yet pushing out via CI, but we are very close to it!

**Pull request merged**
