### PR TITLE
fix syslog reload

### PR DESCRIPTION
**Pull request by andres-h**

### CODE REVIEW

**Comment by hyperknot** [comment]
Looks nice, but apparently syslog-ng has a memory leak when receiving HUP signal. Can you try it with the version we are using?

https://github.com/balabit/syslog-ng/issues/1317

**Comment by andres-h** [comment]
> Looks nice, but apparently syslog-ng has a memory leak when receiving HUP signal. Can you try it with the version we are using?

I'm using the version of syslog-ng that comes with baseimage-docker. Wasn't aware of the issue... But "sv reload" also sends HUP, so it must have the same issue. "sv reload" just don't work, because syslog is no longer a runit service.

**Comment by hyperknot** [comment]
You are right, we were using reload, not restart so it should be the same. Probably with weekly reloads it never caused a big issue for anyone, so it's safe I guess.

**Comment by hyperknot** [comment]
BTW, the issue you've just fixed is #469.

**Pull request merged**
