### PR TITLE
wait-for-services script

### LINKED ISSUE #44: my_init should have a mechanism to wait until all Runit services are started
I'm having around 300 images based on  baseimage-docker and I'm running a script that will run a command on each of those (with `/sbin/my_init --` as an  entry point), wait for it to finish, do stuff, run next...

Several times, container hang with this message as last thing in log:

```
warning: /etc/service/cron: unable to open supervise/ok: file does not exist
```

except any of the cron / syslog / ssh could fail with this message.

I'm not having a reliable way to reproduce this.

### PR DESCRIPTION
**Pull request by bukzor**
closes #44
Also factors out all sleep calls, and their attendant race conditions.
I tried adding a symlink to `false` as /etc/service/cron/check, and the test correctly failed.

### CODE REVIEW

**Comment by bukzor** [comment]
@phusion ?

**Comment by bukzor** [comment]
I've proposed a couple patches to sv-check behavior that reduces the wait-for-services script to simply `sv check /etc/service/*` again. I'm not entirely hopeful that they will be merged though.

I've started upstream discusion here:
 1. http://www.mail-archive.com/supervision@list.skarnet.org/msg00465.html
 2. http://www.mail-archive.com/supervision@list.skarnet.org/msg00464.html

**Comment by FooBarWidget** [comment]
Sorry, I haven't had time to look at this yet. I'm pretty preoccupied with other projects. But I promise you I will look at it eventually.

**Comment by bukzor** [comment]
Thanks Hongli!
No worries.

--phone is hard.

**Comment by Theaxiom** [comment]
@bukzor This PR has merge conflicts, please resolve those conflicts and let me know so I can merge your changes in! :)

**Comment by bukzor** [comment]
Full disclosure: I don't plan to spend time on this.

**Comment by Theaxiom** [comment]
@bukzor Thank you for letting me know, I will see what I can do regarding your PR. I am trying to get as much of these PR's and Issues resolved as I can. :)

**Comment by hyperknot** [comment]
Can you explain what did you originally wanted to achieve here? What do you mean by "wait for services"? Wait for all services to be started and up? Or wait for a specific service to be running?

What makes it even more tricky is that some services need some proper time to actually initialise even after being "up".

For example, the only proper way to check if PostgreSQL is actually running properly is something like this (100% custom for PostgreSQL):

```
until su - postgres -c '/usr/lib/postgresql/9.5/bin/pg_ctl status -D /data/pgsql/9.5' | grep 'pg_ctl: server is running '
do
    echo
    echo "....waiting for PostgreSQL to start"
    sleep 1
done
sleep 3
echo "PostgreSQL started"
```

**Pull request closed without merging**
