### PR TITLE
From: 16.04 to 18.04

### PR DESCRIPTION
**Pull request by twobombs**
https://github.com/phusion/baseimage-docker/issues/479#issuecomment-400253475

### CODE REVIEW

**Comment by twobombs** [comment]
travis fails because sv doesn't run @18.04 
I replaced the sv command with service ssh start and modded the sv test script, then the build works. 
however, we do have a thing there: sv no workie,so that might break stuff for ppl. 

[](https://travis-ci.org/twobombs/baseimage-docker/jobs/402234578 )

**Comment by kmeekva** [comment]
I thought the phusion baseimage used sv because you the regular service start / stop would not work in docker?  With 18.04 will service command work properly for starting / stoping services?  I liked the being able to tweak configs and restarting them using sv without having to restart the whole container.

**Comment by twobombs** [comment]
service <service> start/stop/restart has worked always, but since supervisord is the thread manager by default sv is the sheriff in base-image town. sv however has rights that are lower then service and on top of that has a servicebus issue that came up intermiddently in 14/16/17 and where I worked around it by calling service <servicename> start/stop/restart in the supervisord init scripts at runtime. *

The trick is that the processes need to stay in line with the supervisord thread manager otherwise you create orphan threads in an instant; eg invoking service <servicename> start/stop/restart inside a container creates orphan threads as it pulls the thread from the sv manager and places them in the non-existant init runtime scheme of things. ( behaviour can be observed/checked with tools such as pstree )

As I don't want to completely defile the base-image repo with the mods ( runtime scripts as mentionioned previously ) & orchestration dependancies I've been using the last 3 years ( *cough* -rancher fixes this elegantly- *cough* ) to work around this.

I think I'm going to withdraw the merge request because the way I and others use base-image is a gotterdammerung for most docker microservice purists :)  

https://twitter.com/solomonstre/status/435986031024668672   

* Could be that 18.04.01 has the fix with that pesky servicebus thingie like previous releases have had. But then again, it could return at a moments' notice.

have a nice day.

**Comment by davidbernick** [comment]
Is there an ETA to getting 18.04 in place? There are a few different open PRs...

**Comment by davidbernick** [comment]
Travis fails because it's waiting for a dockerhub login:
```
The command "env NAME=${NAME} VERSION=${VERSION} ./test/runner.sh" exited with 0.
$ docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"; docker push ${NAME}:${VERSION};
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: 
```

**Comment by twobombs** [comment]
I'm going to close this merge request as the changes required to makes this work will anger the Gods(tm). However: my own fork at my own repo will carry the changes required to make this work. I do not expect the mainline to follow this.

**Comment by Theaxiom** [comment]
@davidbernick We will work to get 18.04 in place very soon, thanks for your patience!

**Pull request closed without merging**
