### PR TITLE
factor out nsenter, in favor of docker exec

### PR DESCRIPTION
**Pull request by bukzor**
Now that we have docker exec, nsenter seems like needless additional complexity.

### CODE REVIEW

**Comment by FooBarWidget** [comment]
nsenter is still there for backward compatibility with people who are on older versions of baseimage-docker, and on older versions of Docker. The entire docker-bash tool will be removed at some point, but that point is not now.

**Comment by bukzor** [comment]
Also, the current docker-bash fails for me entirely.

```
$ ./tools/docker-bash e8
baseimage-docker-nsenter: cannot open /proc/6819/ns/ipc: Permission denied
```

**Comment by FooBarWidget** [comment]
Maybe Docker 1.4 has changed sufficiently that nsenter is no longer compatible.

**Comment by FooBarWidget** [comment]
nsenter has now been phased out as far as documentation is concerned. We still support it for backwards compatibility reasons.

**Pull request closed without merging**
