### PR TITLE
Gracefully handle syslog-ng shutdown

### PR DESCRIPTION
**Pull request by kamermans**
This fixes a minor issue with the shutdown process of `syslog-ng` introduced with PR #425.

The problem is that under some conditions, when you kill the container, `syslog-ng` gets the kill command from the init process before the shutdown sequence, and the `syslog-ng.shutdown` script tries to `cat` syslog-ng's PID file, but it's already gone.

I can reliably reproduce this issue by running the container interactively, then pressing `CTRL-C`, but I suspect it happens also in the wild when docker/docker-compose sends the kill command to the PID 0 init system.

Here's the current effect (note that the image is the current `master` branch with no modifications):
`$ docker run -ti --rm kamermans/phusion-baseimage:0.9.23-rc2`
```
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Nov  1 21:10:04 e0756e33d57f syslog-ng[11]: syslog-ng starting up; version='3.5.6'
Nov  1 21:10:04 e0756e33d57f syslog-ng[11]: WARNING: you are using the pipe driver, underlying file is not a FIFO, it should be used by file(); filename='/dev/stdout'
Nov  1 21:10:05 e0756e33d57f syslog-ng[11]: EOF on control channel, closing connection;
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 17
Nov  1 21:10:05 e0756e33d57f cron[20]: (CRON) INFO (pidfile fd = 3)
Nov  1 21:10:05 e0756e33d57f cron[20]: (CRON) INFO (Running @reboot jobs)
^C
Nov  1 21:10:11 e0756e33d57f syslog-ng[11]: syslog-ng shutting down; version='3.5.6'
*** Shutting down runit daemon (PID 17)...
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
cat: /var/run/syslog-ng.pid: No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
*** /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown failed with status 1

*** Killing all processes...
```

This is the part that I am talking about:
```
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
cat: /var/run/syslog-ng.pid: No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
*** /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown failed with status 1
```

This PR simply checks if the PID file is there before attempting to `cat` it.  Note that there is still technically some chance that the PID file disappears between the `-f` and the `cat`, but it would likely be so rare that it's not worth coding around.

### CODE REVIEW

**Comment by hyperknot** [comment]
> syslog-ng gets the kill command from the init process before the shutdown sequence

If this is true, then we still didn't fix the problem of loosing log files.

**Comment by hyperknot** [comment]
#425 really changed the internal logic of baseimage. Before init.d scripts were short lived, one-time scripts we didn't have to worry about.

Now we have to kind of hard code the whole syslog-ng into my_init, to make sure that we always kill it after everything else.

**Comment by Theaxiom** [comment]
What's the path forward from here?

**Comment by Theaxiom** [comment]
I've raised an issue against this so we can discuss and test further.

**Comment by kamermans** [comment]
Good point @hyperknot - I have only tested, and therefore only confirmed, that it happens when you run it interactively with `-ti` and press `CTRL-C`, but my understanding is that when the Docker daemon sends `SIGTERM` to PID 0, all the children also receive this signal.  Technically speaking, I believe every process in the container is a child of PID 0, so they are all in the same *process group*, and when you send a signal to a process, everyone in that group gets the signal (a cursory search [shows something similar](https://unix.stackexchange.com/questions/176235/fork-and-how-signals-are-delivered-to-processes)).

When I submitted this PR I was simply trying to fix the non-zero exit and error messages, but you're right.  This begs the question "is it even possible to keep `syslog-ng` from catching `SIGTERM` and going down as quickly as possible".  I'll do some testing - maybe PID 0 doesn't normally get the `SIGTERM` directly because of some Docker magic, but it certainly seems to when being run interactively (`CTRL-C` sends `SIGTERM` to the active process, which is always PID 0 when you run `-ti`).

**Comment by kamermans** [comment]
I've done some testing an realize, you aren't sending `SIGTERM` when you hit `CRTL-C`, you're sending `SIGINT`, and it seems this is what makes all the difference.

For my testing I made this python script:
`/tmp/logger.py`
```python
#!/usr/bin/env python3

import signal, sys, syslog
from time import sleep
from datetime import datetime

def receive_signal(signum, stack):
    #if signum in [1,2,3,15]:
    #    print '[%s] Caught signal %s, exiting.' % (datetime.now().strftime("%H:%M:%S.%f"), SIGNALS_NAMES[signum])
    #else:
    print('[%s] Caught signal %s, ignoring.' % (datetime.now().strftime("%H:%M:%S.%f"), signal.Signals(signum).name))

def main():
    catchable_sigs = set(signal.Signals) - {signal.SIGKILL, signal.SIGSTOP}
    for sig in catchable_sigs:
        signal.signal(sig, receive_signal)

    syslog.openlog(logoption=syslog.LOG_PID, facility=syslog.LOG_DAEMON)

    msg = "[%s] Starting" % datetime.now().strftime("%H:%M:%S.%f")
    print(msg)
    syslog.syslog(syslog.LOG_WARNING, msg)

    while True:
        msg = "[%s] Ping" % datetime.now().strftime("%H:%M:%S.%f")
        print(msg)
        syslog.syslog(syslog.LOG_WARNING, msg)
        sleep(0.25)

main()
```

It simply logs a message with the time 4 times per second to STDOUT and Syslog, so we can see if anything gets dropped.  The script ignores catchable signals so it can simulate a busy process that might stay alive longer than `syslog-ng`.

First, I tested the `CTRL-C` scenario:
```
$ docker run -ti --rm --name test -v /tmp/logger.py:/etc/my_init.d/logger.py 8875b6b6069
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Nov  2 23:46:24 0e3c06313405 syslog-ng[11]: syslog-ng starting up; version='3.5.6'
Nov  2 23:46:24 0e3c06313405 syslog-ng[11]: WARNING: you are using the pipe driver, underlying file is not a FIFO, it should be used by file(); filename='/dev/stdout'
Nov  2 23:46:25 0e3c06313405 syslog-ng[11]: EOF on control channel, closing connection;
*** Running /etc/my_init.d/logger.py...
[23:46:25.256961] Starting
[23:46:25.257046] Ping
Nov  2 23:46:25 0e3c06313405 /logger.py[16]: [23:46:25.256961] Starting
Nov  2 23:46:25 0e3c06313405 /logger.py[16]: [23:46:25.257046] Ping
[23:46:25.507380] Ping
Nov  2 23:46:25 0e3c06313405 /logger.py[16]: [23:46:25.507380] Ping
[23:46:25.757852] Ping
Nov  2 23:46:25 0e3c06313405 /logger.py[16]: [23:46:25.757852] Ping
[23:46:26.008337] Ping
Nov  2 23:46:26 0e3c06313405 /logger.py[16]: [23:46:26.008337] Ping
[23:46:26.258812] Ping
Nov  2 23:46:26 0e3c06313405 /logger.py[16]: [23:46:26.258812] Ping
[23:46:26.509315] Ping
Nov  2 23:46:26 0e3c06313405 /logger.py[16]: [23:46:26.509315] Ping
^CNov  2 23:46:26 0e3c06313405 syslog-ng[11]: syslog-ng shutting down; version='3.5.6'
[23:46:26.564539] Caught signal SIGINT, ignoring.
*** An error occurred. Aborting.
*** Shutting down /etc/my_init.d/logger.py (PID 16)...
[23:46:26.564802] Caught signal SIGTERM, ignoring.
[23:46:26.759730] Ping
[23:46:27.010253] Ping
[23:46:27.260728] Ping
 ... truncated repeated lines ... 
[23:46:31.017962] Ping
[23:46:31.268447] Ping
[23:46:31.518925] Ping
*** /etc/my_init.d/logger.py (PID 16) did not shut down in time. Forcing it to exit.
*** Init system aborted.
*** Killing all processes...
```

As you can see, in this scenario `syslog-ng` dies first, and all the log data between `SIGINT` and `SIGKILL` is lost from the syslog stream.

Then I tested the normal scenario, where Docker does the `SIGTERM`:
```
$ docker run -ti --rm --name test -v /tmp/logger.py:/etc/my_init.d/logger.py 8875b6b6069
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Nov  3 00:00:37 96cc44366c64 syslog-ng[11]: syslog-ng starting up; version='3.5.6'
Nov  3 00:00:37 96cc44366c64 syslog-ng[11]: WARNING: you are using the pipe driver, underlying file is not a FIFO, it should be used by file(); filename='/dev/stdout'
Nov  3 00:00:38 96cc44366c64 syslog-ng[11]: EOF on control channel, closing connection;
*** Running /etc/my_init.d/logger.py...
[00:00:38.554953] Starting
[00:00:38.555030] Ping
Nov  3 00:00:38 96cc44366c64 /logger.py[16]: [00:00:38.554953] Starting
Nov  3 00:00:38 96cc44366c64 /logger.py[16]: [00:00:38.555030] Ping
[00:00:38.805366] Ping
Nov  3 00:00:38 96cc44366c64 /logger.py[16]: [00:00:38.805366] Ping
[00:00:39.055846] Ping
Nov  3 00:00:39 96cc44366c64 /logger.py[16]: [00:00:39.055846] Ping
[00:00:39.306343] Ping
Nov  3 00:00:39 96cc44366c64 /logger.py[16]: [00:00:39.306343] Ping
[00:00:39.556810] Ping
Nov  3 00:00:39 96cc44366c64 /logger.py[16]: [00:00:39.556810] Ping
*** An error occurred. Aborting.
*** Shutting down /etc/my_init.d/logger.py (PID 16)...
[00:00:39.799520] Caught signal SIGTERM, ignoring.
[00:00:39.807076] Ping
Nov  3 00:00:39 96cc44366c64 /logger.py[16]: [00:00:39.807076] Ping
[00:00:40.057496] Ping
Nov  3 00:00:40 96cc44366c64 /logger.py[16]: [00:00:40.057496] Ping
[00:00:40.307973] Ping
Nov  3 00:00:40 96cc44366c64 /logger.py[16]: [00:00:40.307973] Ping
 ... truncated repeated lines ... 
[00:00:44.065152] Ping
Nov  3 00:00:44 96cc44366c64 /logger.py[16]: [00:00:44.065152] Ping
[00:00:44.315639] Ping
Nov  3 00:00:44 96cc44366c64 /logger.py[16]: [00:00:44.315639] Ping
[00:00:44.566082] Ping
Nov  3 00:00:44 96cc44366c64 /logger.py[16]: [00:00:44.566082] Ping
*** /etc/my_init.d/logger.py (PID 16) did not shut down in time. Forcing it to exit.
*** Init system aborted.
*** Killing all processes...
Nov  3 00:00:44 96cc44366c64 syslog-ng[11]: syslog-ng shutting down; version='3.5.6'
```

In this test, the syslog data is preserved.

It did occur to me that these tests are sort of bad because they are happening in the `init` process, so I also tested it as a `runit` service, being killed as usual by Docker:

```
$ docker run -ti --rm --name test -v /tmp/logger.py:/etc/service/test-service/run 8875b6b6069
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Nov  3 00:02:51 8276a5f1ae68 syslog-ng[11]: syslog-ng starting up; version='3.5.6'
Nov  3 00:02:51 8276a5f1ae68 syslog-ng[11]: WARNING: you are using the pipe driver, underlying file is not a FIFO, it should be used by file(); filename='/dev/stdout'
Nov  3 00:02:52 8276a5f1ae68 syslog-ng[11]: EOF on control channel, closing connection;
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 17
Nov  3 00:02:52 8276a5f1ae68 cron[22]: (CRON) INFO (pidfile fd = 3)
Nov  3 00:02:52 8276a5f1ae68 cron[22]: (CRON) INFO (Running @reboot jobs)
[00:02:52.190702] Starting
[00:02:52.190804] Ping
Nov  3 00:02:52 8276a5f1ae68 /run[21]: [00:02:52.190702] Starting
Nov  3 00:02:52 8276a5f1ae68 /run[21]: [00:02:52.190804] Ping
[00:02:52.440928] Ping
Nov  3 00:02:52 8276a5f1ae68 /run[21]: [00:02:52.440928] Ping
[00:02:52.691383] Ping
Nov  3 00:02:52 8276a5f1ae68 /run[21]: [00:02:52.691383] Ping
[00:02:52.941846] Ping
 ... truncated repeated lines ... 
[00:02:53.693266] Ping
Nov  3 00:02:53 8276a5f1ae68 /run[21]: [00:02:53.693266] Ping
[00:02:53.943711] Ping
Nov  3 00:02:53 8276a5f1ae68 /run[21]: [00:02:53.943711] Ping
[00:02:54.194185] Ping
Nov  3 00:02:54 8276a5f1ae68 /run[21]: [00:02:54.194185] Ping
[00:02:54.234915] Caught signal SIGTERM, ignoring.
[00:02:54.235383] Caught signal SIGCONT, ignoring.
[00:02:54.444620] Ping
Nov  3 00:02:54 8276a5f1ae68 /run[21]: [00:02:54.444620] Ping
[00:02:54.695075] Ping
Nov  3 00:02:54 8276a5f1ae68 /run[21]: [00:02:54.695075] Ping
[00:02:54.945533] Ping
Nov  3 00:02:54 8276a5f1ae68 /run[21]: [00:02:54.945533] Ping
 ... truncated repeated lines ... 
[00:02:58.952959] Ping
Nov  3 00:02:58 8276a5f1ae68 /run[21]: [00:02:58.952959] Ping
[00:02:59.203432] Ping
Nov  3 00:02:59 8276a5f1ae68 /run[21]: [00:02:59.203432] Ping
[00:02:59.453901] Ping
Nov  3 00:02:59 8276a5f1ae68 /run[21]: [00:02:59.453901] Ping
*** Shutting down runit daemon (PID 17)...
[00:02:59.704328] Ping
Nov  3 00:02:59 8276a5f1ae68 /run[21]: [00:02:59.704328] Ping
[00:02:59.954825] Ping
Nov  3 00:02:59 8276a5f1ae68 /run[21]: [00:02:59.954825] Ping
[00:03:00.205288] Ping
 ... truncated repeated lines ... 
[00:03:03.711666] Ping
Nov  3 00:03:03 8276a5f1ae68 /run[21]: [00:03:03.711666] Ping
[00:03:03.962108] Ping
Nov  3 00:03:03 8276a5f1ae68 /run[21]: [00:03:03.962108] Ping
[00:03:04.212550] Ping
Nov  3 00:03:04 8276a5f1ae68 /run[21]: [00:03:04.212550] Ping
```

I think this test shows that the improved `syslog-ng`  shutdown code does in fact preserve as much data as possible.  Obviously there may still be some concern about the approach, but it does seem to work.

**Comment by sundbry** [comment]
I think the best way to patch this would be to mask/catch SIGINT in the bash syslog-ng.startup script, so users get the full log output in the interactive case too.

my_init will follow-up with invoking the shutdown script as demonstrated here, so it will still get shutdown when there's a SIGINT if we mask it out in the startup script, just not prematurely.

**Comment by Theaxiom** [comment]
@sundbry Would you mind creating an issue regarding your suggestion and then we can proceed to merge this PR in the meantime? Thanks!

**Comment by sundbry** [comment]
@Theaxiom @kamermans @hyperknot Please review this resolution here when you have a moment.

https://github.com/phusion/baseimage-docker/pull/453

Cheers

**Pull request merged**
