### PR TITLE
Added install_clean.sh utility

### PR DESCRIPTION
**Pull request by kamermans**
This PR adds a utility called `install_clean.sh`, which is a drop-in replacement for `apt-get -y install`, but cleans up after itself.  It passes all of its arguments directly to `apt-get -y install` unaltered, then deletes the `apt` caches after installation to allow derived Docker images to easily install packages without leaving unnecessary files laying around.

Here's an example of how we use it at our organization:

```
FROM phusion/baseimage

RUN install_clean.sh \
        ca-certificates \
        nginx \
        nginx-module-geoip \
        gettext-base \
        libfcgi0ldbl \
    && rm /etc/nginx/conf.d/*

# Used to run health checks against the FCGI backend
ADD https://gist.githubusercontent.com/kamermans/fab681a9dd8be3e4d6dd/raw/fcgi_get.sh /usr/local/bin/fcgi_get.sh

RUN chmod +x /usr/local/bin/fcgi_get.sh \
    && ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

RUN echo '\n# Mitigate httpoxy attack\nfastcgi_param  HTTP_PROXY         "";' >> /etc/nginx/fastcgi_params

COPY resources/service /etc/service
COPY resources/sites/*.conf /etc/nginx/conf.d/

EXPOSE 80 443
```

### CODE REVIEW

**Comment by hyperknot** [comment]
Looks useful. Can we add `--no-install-recommends` as well?

**Comment by kamermans** [comment]
Sure, if you want - we used to have that as the default, but we ended up changing it over time.  I think it's a perfectly reasonable default though.

**Comment by kamermans** [comment]
Oh, wait, how do you force the system to install recommends then?  I could add a check to `--install-recommends` that prevents the addition of `--no-install-recommends`

**Comment by hyperknot** [comment]
Looks nice, but should it end with `.sh`, in `/sbin`? What is the naming convention, isn't clean command names preferred?

**Comment by kamermans** [comment]
Good point, in my images it's in `/usr/local/bin`, where things are a little more "wild-west", but if you prefer to have it match the normal convention like the other utils, I have no issue with that.  I think that my original reasoning was that the `.sh` made it obvious that it wasn't some little-known program that got pulled in from some repo or something.

I think getting pulled into the baseimage it might be best to strip off the `.sh` - I'll update it a sec...

**Comment by rdxmb** [comment]
just a question @hyperknot : 
in the prepare.sh (and several others) you use the
`$minimal_apt_get_install` (Do not know at the moment where this is defined.)

Could we put these two things together in any way, so we have not a "wild-west" for that? ;)
Especially in a baseimage - we should have ONE thing and way for the same issue.

**Comment by hyperknot** [comment]
@rdxmb that one is loaded from https://github.com/phusion/baseimage-docker/blob/master/image/buildconfig, which is sourced from most install scripts of baseimage.

The difference being that install_clean does an apt-get update and cleans the cache after every time it's called. This one makes it quite inefficient for using it multiple times, as you are loading all the repositories for each install, and then deleting them afterwards.

The better solution is $minimal_apt_get_install and removing the cache at the very end of the Dockerfiles, like it's done in Baseimage.

So if picking one solution then I think it should be `$minimal_apt_get_install`.

**Comment by kamermans** [comment]
When building a `Dockerfile`, you definitely don't want to clear the cache at the end of the `Dockerfile`, otherwise the apt-cache will remain in all the intermediate layers.

In Phusion you solve this problem by putting everything in a script, then calling the script from a single `RUN` command in your `Dockerfile`:
```
RUN /bd_build/prepare.sh && \
	/bd_build/system_services.sh && \
	/bd_build/utilities.sh && \
	/bd_build/cleanup.sh
```

This works great in a base image, but images derived from this one are more manageable when you can see the individual steps in the `Dockerfile` itself.  We use this utility throughout our 50+ maintained images as a drop-in replacement for `apt-get install`, so you can replace this very common practice:
```
# From: https://github.com/jwilder/nginx-proxy/blob/master/Dockerfile#L4-L10
RUN apt-get update \
 && apt-get install -y -q --no-install-recommends \
    ca-certificates \
    wget \
 && apt-get clean \
 && rm -r /var/lib/apt/lists/*
```

With a more sane practice:
```
RUN install_clean wget ca-certificates
```

**Comment by kingdonb** [comment]
Updating this branch to merge it.  I am definitely in favor of anything that makes the Dockerfile easier to follow.

**Pull request merged**
