### PR TITLE
Added /etc/my_cron support

### PR DESCRIPTION
**Pull request by kamermans**
Traditionally, cron jobs will not be run (and in some cases silently fail) if they do not match a very specific set of criteria (owned by `root`, `chmod 0644`, cannot have an extension like `.sh`, etc) .  This presents a problem when have a custom cron job that you want to mount into `/etc/cron.d/`.  If you want it to run, you need to `chown root:root && chmod 0644` the file, but if you do that, you change the file on the host, probably making it impossible for you to edit (or switch git branches, etc).

With this PR you can copy or mount your cron jobs into `/etc/my_cron.d/`, `/etc/my_cron.hourly/`, `/etc/my_cron.daily/`, `/etc/my_cron.weekly/` and/or `/etc/my_cron.monthly/`, and when the container starts, it will copy them to the appropriate directory, fix their permissions and clean their filenames automatically.

Example:

	docker run \
		-v $(pwd)/somecronjob:/etc/my_cron.d/somecronjob:ro \
		-v $(pwd)/daily_job.sh:/etc/my_cron.daily/daily_job.sh:ro \
		YOUR_IMAGE

### CODE REVIEW

**Comment by hyperknot** [comment]
I'm not 100% sure on this one, might be a bit too much of an edge case. Why not just `find ... -exec chmod 644` the whole folder on startup?

**Comment by kamermans** [comment]
The file permissions are only part of it.  From what I recall, the user and group also need to be `root`, which means you really can't mount a cron job into the container, and files in `/etc/cron.(hourly|daily|weekly)` must be `755` with a very strange naming convention (no file extensions, for example).

**Comment by Alexhha** [comment]
Instead of 
```
mkdir /etc/my_cron.d
mkdir /etc/my_cron.hourly
mkdir /etc/my_cron.daily
mkdir /etc/my_cron.weekly
mkdir /etc/my_cron.monthly
```

you can use just one command
```
mkdir /etc/my_cron.{d,hourly,daily,weekly,monthly}
```

**Comment by BunnyHolder** [comment]
Or just `crontab /some/path/my_cron_file`

**Comment by mech** [comment]
Is this somehow the reason why cron job can't run in another user says "app" for passenger-docker when used under Rails context?

**Pull request closed without merging**
