### PR TITLE
WIP: Build armhf

### PR DESCRIPTION
**Pull request by kingdonb**
Copy Dockerfile with a minor substitution for armhf, and register qemu on the build machine

### CODE REVIEW

**Comment by kingdonb** [comment]
```
kingdonb/baseimage           0.11-armhf          f60baaf0e301        15 minutes ago      189MB
kingdonb/baseimage           armhf-latest        f60baaf0e301        15 minutes ago      189MB
kingdonb/baseimage           0.11                d9bf3702bd93        21 minutes ago      186MB
kingdonb/baseimage           latest              d9bf3702bd93        21 minutes ago      186MB```

Tests seem to be passing, I haven't looked to see what's up with Travis

**Comment by abrodkin** [comment]
One tiny note - why don't we use x86 base from the same multiarch image so that we get exactly the same everything?
```
diff --git a/image-amd64/Dockerfile b/image-amd64/Dockerfile
index da5b41d9fb98..f029cb6732a2 100644
--- a/image-amd64/Dockerfile
+++ b/image-amd64/Dockerfile
@@ -1,4 +1,4 @@
-FROM ubuntu:18.04
+FROM multiarch/ubuntu-core:x86_64-bionic
 MAINTAINER Phusion <info@phusion.nl>
 
 COPY . /bd_build
```

**Comment by kingdonb** [comment]
Well splitting the Dockerfile into two arches an in my proposal presents a number of obstacles for a simple build remote like quay (https://quay.io/repository/kingdonb/baseimage-docker?tab=builds) and yours does not, so tomorrow I'll take the x86_64 multiarch build and see if it can work on armhf.  If that works, I will honestly be shocked, but I haven't done the image size comparison yet, so maybe it's not as shocking as I think.

Does this really work on an armhf deployment target?  I'm skeptical, I honestly wouldn't have tried this on my own, but I haven't read any of the multiarch manuals and @abrodkin suggested it, so it seems worth a shot.

(It would probably have to work without this high-level wizardry:
`docker run --rm --privileged multiarch/qemu-user-static:register --reset`)

It builds:

https://quay.io/repository/kingdonb/baseimage-docker/build/69f84a88-c780-434d-a7bc-daeeb2c9d5b4

It builds on quay.io at least, where I am skeptical that armhf-centric build would have been able to work in any case...

**Comment by abrodkin** [comment]
> Well splitting the Dockerfile into two arches an in my proposal presents a number of obstacles for a simple build remote like quay (https://quay.io/repository/kingdonb/baseimage-docker?tab=builds)

Unfortunately I cannot access referenced build logs (Quay says I must be an admin of the repo - why???) so not sure what goes wrong there.

> and yours does not, so tomorrow I'll take the x86_64 multiarch build and see if it can work on armhf. If that works, I will honestly be shocked, but I haven't done the image size comparison yet, so maybe it's not as shocking as I think.

I'm wondering what are you going to achieve here? "x86_64 multiarch" is base container for 64-bit x86 and I guess is not usable as a base for ARM 64-bit anything. BTW given simpler `armhf` works it might be more beneficial for users than `arcm64` (note even though there're quite some mainline distros already available in 64-bit form for RPi3 like Fedora, Gentoo etc still Raspbian only has 32-bit official image).

> Does this really work on an armhf deployment target? I'm skeptical, I honestly wouldn't have tried this on my own, but I haven't read any of the multiarch manuals and @abrodkin suggested it, so it seems worth a shot.

What I tried was cross-building on `x86_64` for `armhf` and ten tested built container on 32-bit Raspbian.

> (It would probably have to work without this high-level wizardry:
> `docker run --rm --privileged multiarch/qemu-user-static:register --reset`)
> 
> It builds:
> 
> https://quay.io/repository/kingdonb/baseimage-docker/build/69f84a88-c780-434d-a7bc-daeeb2c9d5b4
> 
> It builds on quay.io at least, where I am skeptical that armhf-centric build would have been able to work in any case...

May I have access to built container so I may try it on real RPi?

**Comment by kingdonb** [comment]
Ah I see

It sounded like a pipe-dream having one image that could run on both armhf and x86_64 (and who knows how many other arch are supported by multiarch), so thanks for explaining what you meant.

The first builds failed because quay.io was looking to the master branch to determine the location of the Dockerfile and image context (which I think I had moved in bbff66a) -- so the Dockerfile was no longer in /image, so the build failed... simple enough

I have a feeling that still would not have worked even if I updated the build target, because you need to register the qemu thing in order to build armhf targets on a different-arch host, and that has to be done in privileged mode (and doing that affects the build host state, what build host is going to allow that...)

So I would guess you hit the same issue building on dockerhub, but I don't really know exactly what we're using for our image tagging pipeline now.

I am actually not sure why my quay builds are private, I do not have a paid quay account so I should not be able to make private builds:

> This Repository is currently public and is visible to all users, and may be pulled by all users.
> In order to make this repository private under your personal namespace , you will need to upgrade the namespace's plan to at least a Developer plan.

You can pull as: `docker pull quay.io/kingdonb/baseimage-docker:build-armhf`

...but it's not going to work right now, as you said... this was a misguided attempt.  So wait until after lunch and I'll hopefully have found a way to automate this build so it works with rpi3.

**Comment by kingdonb** [comment]
Note: I was not able to get quay to automate building of armhf images, but the image that I built from my macbook is here, and I verified that it pulls with no authentication:

`docker pull quay.io/kingdonb/baseimage:build-armhf`

This is going to present an obstacle to support, if there is no public cloud environment that offers a free way to build armhf images.  I don't think that's the end of the line, but I'll have to explore the options.

For some reason it looks like arm64-bionic isn't actually working on the rpi3 though... I get an exec format error once I've pulled the image to the rpi3.  Now trying armhf-bionic instead.

**Comment by kingdonb** [comment]
OK, that worked.  quay.io/kingdonb/baseimage:build-armhf @ IMAGE ID f42768b11340 created 4 minutes ago.

I used the armhf-bionic upstream image, built on macbook.  (So at least we know we don't need a build farm composed of raspberry pi's to think about offering support.)

**Comment by kingdonb** [comment]
So this PR is obviously not in shape to merge at the moment, but...

> One tiny note - why don't we use x86 base from the same multiarch image so that we get exactly the same everything?

Thoughts on this?  I haven't done a size comparison, but one reason not to do this might be if the multiarch image is larger.  (I don't know enough about multiarch to say if this is true or not.)

If it is bigger, but just a little bit bigger... I would probably still keep the smaller image unless there is some compelling advantage to switch to multiarch for the x86_64 build.  (What does it buy you?)

**Comment by kingdonb** [comment]
> I.e. on both x86_64 and armhf I would use exactly the same command docker run awesome_company/mycool-app:v1 echo hi which under the hood will pull platform-specific image and run it.

You're absolutely right, there is magic here (but not the magic I was expecting) and I didn't get it

I will read over that IBM developer article too, thanks for the reference!

**Comment by Theaxiom** [comment]
We will work on the capability to have multiple build targets and using the CI we can automatically release several images, each arch specific.

**Comment by kingdonb** [comment]
I opened a new discussion at #518 -- I don't have time to attack this right now, but you should expect to see this ready before Mid-November as long as my planning calendar doesn't utterly break down

**Pull request closed without merging**
