### PR TITLE
Make default services (syslog-ng, sshd, cron) optional.

### LINKED ISSUE #165: more minimalistic
I like the idea of this image - but frankly speaking for most of my use cases I don't need syslog or cron. It would be great if the base image would be a little more minimalistic - but allows for inclusion of syslog, cron and ssh.

### PR DESCRIPTION
**Pull request by endersonmaia**
Use `image/buildconfig` to make services optional.

fixes #165

### CODE REVIEW

**Comment by endersonmaia** [comment]
How can I change this pull request from `master` to `next` branch ?

**Comment by FooBarWidget** [comment]
Don't worry, I'll take care of it.

**Comment by endersonmaia** [comment]
I'm closing this PR, and will create a new one, since the development branch is now `next` and not `master` anymore. See https://github.com/phusion/baseimage-docker/issues/165#issuecomment-70542331

**Comment by FooBarWidget** [comment]
In my opnion cron and ssh should be removable, but syslog shouldn't, because important messages can get lost. Especially now that we redirect syslog output to "docker logs", I think having a syslog around is important.

**Comment by endersonmaia** [comment]
I closed the PR and just saw your comments now.

Let's talk about it on #182 ?

**Pull request closed without merging**
