### PR TITLE
add "ping" and "ip" to utilities

### PR DESCRIPTION
**Pull request by marcbihlmaier**
for debbugging it is useful to have the simple "ping" and "ip" - commands within the container, don't you think?

### CODE REVIEW

**Comment by hyperknot** [comment]
Sorry, this is clearly not related to "base" image. There are already comments about baseimage being bloated, if we start adding every single helper util where do we stop? 
They have the perfect place in child images.

**Comment by hyperknot** [comment]
I vote for close.

**Comment by kingdonb** [comment]
I agree, especially nmap which is almost 20MB unpacked.

Ping (`iputils-ping`) is very small and I would not object to including it.  The `ip` tool in `iproute2` is pretty important too, I'm not sure how you can find out your own IP address without it, given that we're not providing ifconfig either.

If that's the use case it's needed for though, it would be cheaper to include ifconfig via `net-tools`:

```
Need to get 175 kB of archives.
After this operation, 725 kB of additional disk space will be used.
```

vs. `iproute2` and dependencies `libatm1` `libmnl0` `libxtables11`:

```
Need to get 585 kB of archives.
After this operation, 1,808 kB of additional disk space will be used.
```

I'm not sure if the `ifconfig` suite is dead-end though, I think many distros are not providing it anymore in favor of `ip`.

**Comment by hyperknot** [comment]
But docker has it's own set of tools for getting the ip addresses, why do we include tools for it? And why in base image? 725 kb is quite small on the other hand, but still, I'm interested in the use case.

**Comment by kingdonb** [comment]
I'm suggesting, but not recommending, that we include Ping.  As we include SSH

Ifconfig I could do without

However, if you closed this issue without comment I would not protest

**Comment by rdxmb** [comment]
Ok, I got it. I already created a "child image" for debugging where I added several tools. For production, I switch back to the "real" base image. Seems quite simple and a very good workflow.

"But docker has it's own set of tools for getting the ip addresses" 
-> I have not found any to find the ip address from *inside* the container yet. But this is not a baseimage-problem, so it's ok for me to close this unmerged. Thanks!

**Comment by marcbihlmaier** [comment]
Ok, I got it. I already created a "child image" for debugging where I added several tools. For production, I switch back to the "real" base image. Seems quite simple and a very good workflow.

"But docker has it's own set of tools for getting the ip addresses"
-> I have not found any to find the ip address from inside the container yet. But this is not a baseimage-problem, so it's ok for me to close this unmerged. Thanks!

**Comment by mahone3297** [comment]
some common utilities, I think we can add it to the base image.
Although we can add it in the child image, but it's common, and I think we can consider install it for easy use.

**Pull request closed without merging**
