### PR TITLE
Make default services (syslog-ng, sshd, cron) optional

### LINKED ISSUE #165: more minimalistic
I like the idea of this image - but frankly speaking for most of my use cases I don't need syslog or cron. It would be great if the base image would be a little more minimalistic - but allows for inclusion of syslog, cron and ssh.

### PR DESCRIPTION
**Pull request by endersonmaia**
Using environment variables to define with services should be installed in the generated images, and split the installation script and config files into the `services/` directory.

Fixes #165

### CODE REVIEW

**Comment by endersonmaia** [comment]
@FooBarWidget you talked about syslog-ng not being optional (https://github.com/phusion/baseimage-docker/pull/166#issuecomment-70547105), but it depends on the objective/statregy of the baseimage distribution.

If you think in the Docker-way (battery included but removable), syslog-ng would be the default logging system, but you could build your own image based on `phusion/baseimage`, but remove syslog-ng and use other logging solution.

Maybe it's too much flexibility if you start thinking it in the `runit` as optional too, but, it's up to you (maintainer) to decide where to limit this flexibility.

What you think ?

**Comment by FooBarWidget** [comment]
This looks mostly good. I have a few comments though:

 * I like what you did with the file renames. But syslog-forwarder should be called syslog-forwarder.runit for consistency.
 * You should update the README and document how services can be disabled using your mechanism.

**Comment by endersonmaia** [comment]
Please, review the docs, since english is not my native language.

**Comment by endersonmaia** [comment]
I just spotted a problem at the merge I did to the `next` branch, I'm fixing it.

- [ ] Fix the merging problem;
- [ ] Send all `ssh` keys and generator files to `/image/services/sshd`.

**Comment by endersonmaia** [comment]
There's a particular thing I'm in doubt, is the section of the documentation. 

The option about the services to be installed is only made possible changing the `image/buildconfig file, and during `docker build` of the `baseimage-docker` project. Projects that are based on  `phusion/baseimage` don't have the option to change it right away.

Thinking about it, maybe the section should be inside "Building the image yourself", at the end of the README. What you think ?

PS.: After review and approval, I'll squash it all.

**Comment by endersonmaia** [comment]
@FooBarWidget , what do you think about the last commit ?

Now there's two ways of removing the services, editing the `buildconfig` file, or defining `ENV` inside your Dockerfile.

**Comment by endersonmaia** [comment]
Any chances this PR gets to 0.9.17 ?

**Comment by FooBarWidget** [comment]
I'm looking into it. After a long time I've finally had some time for baseimage-docker maintenance.

**Comment by FooBarWidget** [comment]
Sorry for the long response. Everything looks good, though there are two issues right now:

1. The documentation looks good, but please move it as a subsection under "Building the image yourself".
2. The cron and syslog-ng scripts are outdated, because there have been several commits recently that touch those parts. Please update those scripts.

Do you think you can do this today or tomorrow? If so I'll bundle it in 0.9.17.

**Comment by endersonmaia** [comment]
- [x] README section moved under "Build the image yourself"
- [x] Updated cron scripts (removing unused cron)
- [x] Updated syslog-ng script (added `syslog-ng.conf`)
- [x] Adjusted all references to insecure_key to the new path (`services/sshd/keys/insecure_key*`)

Can you review/test it ?

**Comment by FooBarWidget** [comment]
Looks good from a first review. Let me test it now.

**Comment by FooBarWidget** [comment]
All right, it has been merged. Thank you!

**Comment by endersonmaia** [comment]
I tryed various combinations os DISABLE_*, and spot a bug.

Should I make a new PR (on master or next?), since this one is closed ?

**Comment by FooBarWidget** [comment]
Yes please do.

**Pull request merged**
